In [1]:
%mamba install pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 5.124399999999907 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [68]:
#transform on the wrong date
#1. load the data
import pandas as pd

df = pd.read_csv('Loan_Data.csv')
print(df)

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No
1    LP001003    Male     Yes          1      Graduate            No
2    LP001005    Male     Yes          0      Graduate           Yes
3    LP001006    Male     Yes          0  Not Graduate            No
4    LP001008    Male      No          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
609  LP002978  Female      No          0      Graduate            No
610  LP002979    Male     Yes         3+      Graduate            No
611  LP002983    Male     Yes          1      Graduate            No
612  LP002984    Male     Yes          2      Graduate            No
613  LP002990  Female      No          0      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]

In [72]:
#2. exploration for wrong datafor col in df.columns:
unique_cols = df[col].unique()
print(f"The unique values in every column are : \n{unique_cols}")

The unique values in every column are :
<StringArray>
['Y', 'N']
Length: 2, dtype: str

In [73]:
#to change the wrong data on dependent column
print(df[df['Dependents']=='3+'])
print(df[df['Dependents']=='3+']['Loan_ID'])

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
7    LP001014    Male     Yes         3+      Graduate            No
34   LP001100    Male      No         3+      Graduate            No
61   LP001206    Male     Yes         3+      Graduate            No
68   LP001238    Male     Yes         3+  Not Graduate           Yes
73   LP001250    Male     Yes         3+  Not Graduate            No
74   LP001253    Male     Yes         3+      Graduate           Yes
78   LP001263    Male     Yes         3+      Graduate            No
79   LP001264    Male     Yes         3+  Not Graduate           Yes
109  LP001384    Male     Yes         3+  Not Graduate            No
126  LP001448     NaN     Yes         3+      Graduate            No
135  LP001488    Male     Yes         3+      Graduate            No
155  LP001536    Male     Yes         3+      Graduate            No
171  LP001585     NaN     Yes         3+      Graduate            No
172  LP001586    Male     Yes         3+  Not Graduate            No
177  LP001610    Male     Yes         3+      Graduate            No
202  LP001682    Male     Yes         3+  Not Graduate            No
211  LP001711    Male     Yes         3+      Graduate            No
213  LP001715    Male     Yes         3+  Not Graduate           Yes
215  LP001720    Male     Yes         3+  Not Graduate            No
255  LP001846  Female      No         3+      Graduate            No
257  LP001854    Male     Yes         3+      Graduate            No
259  LP001864    Male     Yes         3+  Not Graduate            No
267  LP001882    Male     Yes         3+      Graduate            No
295  LP001949    Male     Yes         3+      Graduate           NaN
321  LP002053    Male     Yes         3+      Graduate            No
324  LP002065    Male     Yes         3+      Graduate            No
338  LP002113  Female      No         3+  Not Graduate            No
340  LP002115    Male     Yes         3+  Not Graduate            No
343  LP002126    Male     Yes         3+  Not Graduate            No
352  LP002141    Male     Yes         3+      Graduate            No
359  LP002160    Male     Yes         3+      Graduate            No
376  LP002219    Male     Yes         3+      Graduate            No
390  LP002255    Male      No         3+      Graduate            No
391  LP002262    Male     Yes         3+      Graduate            No
409  LP002317    Male     Yes         3+      Graduate            No
442  LP002418    Male      No         3+  Not Graduate            No
461  LP002484    Male     Yes         3+      Graduate            No
466  LP002500    Male     Yes         3+  Not Graduate            No
472  LP002519    Male     Yes         3+      Graduate            No
481  LP002536    Male     Yes         3+  Not Graduate            No
515  LP002659    Male     Yes         3+      Graduate            No
522  LP002692    Male     Yes         3+      Graduate           Yes
531  LP002720    Male     Yes         3+      Graduate            No
539  LP002740    Male     Yes         3+      Graduate            No
557  LP002795    Male     Yes         3+      Graduate           Yes
567  LP002837    Male     Yes         3+      Graduate            No
574  LP002863    Male     Yes         3+      Graduate            No
592  LP002933     NaN      No         3+      Graduate           Yes
600  LP002949  Female      No         3+      Graduate           NaN
602  LP002953    Male     Yes         3+      Graduate            No
610  LP002979    Male     Yes         3+      Graduate            No

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
7               3036             2504.0       158.0             360.0
34             12500             3000.0       320.0             360.0
61              3029                0.0        99.0             360.0
68              7100                0.0       125.0              60.0
73              4755                0.0        95.0               NaN
74              5266             1774.0       187.0             360.0
78              3167             4000.0       180.0             300.0
79              3333             2166.0       130.0             360.0
109             2071              754.0        94.0             480.0
126            23803                0.0       370.0             360.0
135             4000             7750.0       290.0             360.0
155            39999                0.0       600.0             180.0
171            51763                0.0       700.0             300.0
172             3522                0.0        81.0             180.0
177             5516            11300.0       495.0             360.0
202             3992                0.0         NaN             180.0
211             3430             1250.0       128.0             360.0
213             5703                0.0       130.0             360.0
215             3850              983.0       100.0             360.0
255             3083                0.0       255.0             360.0
257             5250                0.0        94.0             360.0
259             4931                0.0       128.0             360.0
267             4333             1811.0       160.0             360.0
295             4416             1250.0       110.0             360.0
321             4342              189.0       124.0             360.0
324            15000                0.0       300.0             360.0
338             1830                0.0         NaN             360.0
340             2647             1587.0       173.0             360.0
343             3173                0.0        74.0             360.0
352             2666             2083.0        95.0             360.0
359             5167             3167.0       200.0             360.0
376             8750             4996.0       130.0             360.0
390             9167                0.0       185.0             360.0
391             9504                0.0       275.0             360.0
409            81000                0.0       360.0             360.0
442             4707             1993.0       148.0             360.0
461             7740                0.0       128.0             180.0
466             2947             1664.0        70.0             180.0
472             4691                0.0       100.0             360.0
481             3095                0.0       113.0             360.0
515             3466             3428.0       150.0             360.0
522             5677             1424.0       100.0             360.0
531             4281                0.0       100.0             360.0
539             6417                0.0       157.0             180.0
557            10139                0.0       260.0             360.0
567             3400             2500.0       123.0             360.0
574             6406                0.0       150.0             360.0
592             9357                0.0       292.0             360.0
600              416            41667.0       350.0             180.0
602             5703                0.0       128.0             360.0
610             4106                0.0        40.0             180.0

     Credit_History Property_Area Loan_Status
7               0.0     Semiurban           N
34              1.0         Rural           N
61              1.0         Urban           Y
68              1.0         Urban           Y
73              0.0     Semiurban           N
74              1.0     Semiurban           Y
78              0.0     Semiurban           N
79              NaN     Semiurban           Y
109             1.0     Semiurban           Y
126             1.0         Rural           Y
135             1.0     Semiurban           N
155             0.0     Semiurban           Y
171             1.0         Urban           Y
172             1.0         Rural           N
177             0.0     Semiurban           N
202             1.0         Urban           N
211             0.0     Semiurban           N
213             1.0         Rural           Y
215             1.0     Semiurban           Y
255             1.0         Rural           Y
257             1.0         Urban           N
259             NaN     Semiurban           N
267             0.0         Urban           Y
295             1.0         Urban           Y
321             1.0     Semiurban           Y
324             1.0         Rural           Y
338             0.0         Urban           N
340             1.0         Rural           N
343             1.0     Semiurban           Y
352             1.0         Rural           Y
359             1.0     Semiurban           Y
376             1.0         Rural           Y
390             1.0         Rural           Y
391             1.0         Rural           Y
409             0.0         Rural           N
442             1.0     Semiurban           Y
461             1.0         Urban           Y
466             0.0         Urban           N
472             1.0     Semiurban           Y
481             1.0         Rural           Y
515             1.0         Rural           Y
522             1.0         Rural           Y
531             1.0         Urban           Y
539             1.0         Rural           Y
557             1.0     Semiurban           Y
567             0.0         Rural           N
574             1.0     Semiurban           N
592             1.0     Semiurban           Y
600             NaN         Urban           N
602             1.0         Urban           Y
610             1.0         Rural           Y
7      LP001014
34     LP001100
61     LP001206
68     LP001238
73     LP001250
74     LP001253
78     LP001263
79     LP001264
109    LP001384
126    LP001448
135    LP001488
155    LP001536
171    LP001585
172    LP001586
177    LP001610
202    LP001682
211    LP001711
213    LP001715
215    LP001720
255    LP001846
257    LP001854
259    LP001864
267    LP001882
295    LP001949
321    LP002053
324    LP002065
338    LP002113
340    LP002115
343    LP002126
352    LP002141
359    LP002160
376    LP002219
390    LP002255
391    LP002262
409    LP002317
442    LP002418
461    LP002484
466    LP002500
472    LP002519
481    LP002536
515    LP002659
522    LP002692
531    LP002720
539    LP002740
557    LP002795
567    LP002837
574    LP002863
592    LP002933
600    LP002949
602    LP002953
610    LP002979
Name: Loan_ID, dtype: str

In [74]:
df.replace({'Dependents': {'3+':3}},inplace = True)
print(df['Dependents'].unique())

['0' '1' '2' 3 nan]

In [75]:
#2.missing data
#missing data exploration
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [76]:
#Gender,Married,Dependents,Self_Employed are the columns with missing values that can be altered - these are discrete values.
#adding the missing values - since these are categorical, we are going with mode()[0]
df.fillna({
    'Gender':df['Gender'].mode()[0],
    'Married':df['Married'].mode()[0],
    'Dependents':df['Dependents'].mode()[0],
    'Self_Employed':df['Self_Employed'].mode()[0]
},inplace = True)
print(df)
print(df.isnull().sum())
print(df['Gender'].unique())
print(df['Married'].unique())
print(df['Dependents'].unique())
print(df['Self_Employed'].unique())

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No
1    LP001003    Male     Yes          1      Graduate            No
2    LP001005    Male     Yes          0      Graduate           Yes
3    LP001006    Male     Yes          0  Not Graduate            No
4    LP001008    Male      No          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
609  LP002978  Female      No          0      Graduate            No
610  LP002979    Male     Yes          3      Graduate            No
611  LP002983    Male     Yes          1      Graduate            No
612  LP002984    Male     Yes          2      Graduate            No
613  LP002990  Female      No          0      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]
Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
['0' '1' '2' 3]
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [77]:
df.dropna(inplace=True)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [78]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [79]:
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents            object
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [80]:
df['Dependents'] =  df['Dependents'].astype('int64')
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].astype('int')
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents             int64
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term       int32
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [81]:
df.drop(columns = ['Loan_ID'],inplace = True)

In [82]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360,1.0,Rural,Y
610,Male,Yes,3,Graduate,No,4106,0.0,40.0,180,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360,0.0,Semiurban,N

In [83]:
for col in df.columns:
    unique =  df[col].unique()
    print(unique)

<StringArray>
['Male', 'Female']
Length: 2, dtype: str
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
[1 0 2 3]
<StringArray>
['Graduate', 'Not Graduate']
Length: 2, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
[ 4583  3000  2583  6000  5417  2333  3036  4006 12841  3200  2500  3073
  1853  1299  4950  3510  4887  7660  5955  2600  3365  9560  2799  4226
  1442  3750  3167  4692  3500 12500  3667  4166  3748  3600  1800  3941
  5649  5821  2645  4000  1928  3086  4230  4616 11500  2708  2132  3366
  8080  3357  3029  2609  5726 10750  7100  4300  3208  1875  5266  1000
  3846  1378  3988  2366  8566  5695  2958  6250  3273  4133  3620  2484
  1977  4188  1759  4288  4843  3816  3052 11417  7333  3800  2071  5316
  2929  5050 14583  5568 10408  5667  2137  2957 23803 10513  2014  2718
  3459  4895  3316 14999  4200  5042  6950  2698 11757  2330 14866  1538
 10000  4860  6277  2577  9166  2281  3254 39999  9538  2980  1863  7933
  3089  4167  9323  2439  2237  8000  1820 51763  3522  5708  4344  3497
  2045  5516  6400  4600 33846  3625 39147  2178   674  9328  4885 12000
  6033  3858  4191  3125  8333 11000  4923  3917  4408  3244  3975  2479
  3418  3430  7787  5703  3173  3850   150  3727  5000  2221  4009  2971
  3250  4735  4758  2491  3716  3155  5500  3812  3315  5819  2510  2965
  3406  6050  9703  6608  2882  1809  1668  3427  2661 16250  3083  6045
  5250 14683  2060  3481  7200  5166  4095  4708  4333  2876  3237 11146
  2833  2620  3900  2750  3993  3103  4053  3927  2301  1811  3158  3704
  4124  9508  3075  4400  3153  2383  4416  6875  4666  2875  1625  3762
  2400 20233  2917  2927  2507  2473  3399  3717  4342 15000  8666  4917
  5818  4384  2935 63337  9833  4160  2647  2378  4554  2499  3523  2625
  9083  8750  2666  2423  3813  3875  5167  4723  4750  6822  6216  6325
 19730 15759  5185  3062  2764  4817  3069  5391  3333  5941  7167  4566
  2346  5488  9167  9504  1993  3100  3180  3033  3902  1500  2889  2755
  1963  7441  4547  2167  2213  8300 81000  3867  6096  2253  2149  2995
  1600  1025  3246  5829 14880  4606  5935  2920  2717  8624  6500 12876
  2425  1926 10416  7142  3660  7901  4707 37719  3466  4652  3539  3340
  2309  3948  2483  7085  3859  4301  3708  4354  8334  7740  3015  5191
  2947 16692   210  3450  2653  4691  5532 16525  6700  2873 16667  4350
  3095  2083 10833  1958  3547 18333  2435  3691 17263  3597  3326  2895
  6283   645  3159  4865  3814  3583 13262  3598  6065  3283  2130  5815
  2031  3074  4683  3400  2192  5677  7948 17500  3775  5285  2679  6783
  4281  3588 18165  2550  6133  3617  6417  4608  2138  3652  2239  2768
  3358  2526  2785  2454  3593  5468 10139  3887  4180  3675 19484  5923
  5800  8799  3166  3417  5116 16666  6125  6406  3087  3229  1782  3182
  6540  1836  2787  4283  2297  2165  2726  9357 16120  3833  6383  2987
  9963  5780  2894  3676  3987  3232  2900  4106  8072  7583]
[1.50800000e+03 0.00000000e+00 2.35800000e+03 4.19600000e+03
 1.51600000e+03 2.50400000e+03 1.52600000e+03 1.09680000e+04
 7.00000000e+02 1.84000000e+03 8.10600000e+03 2.84000000e+03
 1.08600000e+03 5.62500000e+03 1.91100000e+03 1.91700000e+03
 2.25300000e+03 1.04000000e+03 2.08300000e+03 1.66700000e+03
 3.00000000e+03 1.45900000e+03 7.21000000e+03 1.66800000e+03
 1.21300000e+03 2.33600000e+03 3.44000000e+03 2.27500000e+03
 1.64400000e+03 1.16700000e+03 1.59100000e+03 2.20000000e+03
 2.25000000e+03 2.85900000e+03 3.79600000e+03 3.44900000e+03
 4.59500000e+03 2.25400000e+03 3.06600000e+03 1.87500000e+03
 1.77400000e+03 4.75000000e+03 3.02200000e+03 4.00000000e+03
 1.88100000e+03 2.53100000e+03 2.11800000e+03 4.16700000e+03
 2.90000000e+03 5.65400000e+03 1.82000000e+03 2.30200000e+03
 9.97000000e+02 3.54100000e+03 3.26300000e+03 3.80600000e+03
 7.54000000e+02 1.03000000e+03 1.12600000e+03 3.60000000e+03
 2.33300000e+03 2.28300000e+03 2.14200000e+03 2.66700000e+03
 8.98000000e+03 2.01400000e+03 3.85000000e+03 1.92900000e+03
 7.75000000e+03 3.50000000e+03 1.43000000e+03 2.03400000e+03
 4.48600000e+03 1.42500000e+03 1.66600000e+03 8.30000000e+02
 3.75000000e+03 1.04100000e+03 1.28000000e+03 1.44700000e+03
 3.33300000e+03 1.76900000e+03 7.36000000e+02 1.96400000e+03
 1.61900000e+03 1.13000000e+04 1.45100000e+03 7.25000000e+03
 5.29600000e+03 2.58300000e+03 2.50000000e+03 1.08300000e+03
 1.25000000e+03 3.02100000e+03 9.83000000e+02 1.80000000e+03
 1.77500000e+03 1.71700000e+03 2.79100000e+03 1.69500000e+03
 2.05400000e+03 1.77900000e+03 1.26000000e+03 5.00000000e+03
 1.98300000e+03 5.70100000e+03 1.30000000e+03 4.41700000e+03
 4.33300000e+03 1.84300000e+03 1.86800000e+03 3.89000000e+03
 2.16700000e+03 7.10100000e+03 2.10000000e+03 2.20900000e+03
 3.44700000e+03 1.38700000e+03 1.81100000e+03 1.56000000e+03
 1.85700000e+03 2.22300000e+03 1.84200000e+03 3.27400000e+03
 2.42600000e+03 8.00000000e+02 9.85799988e+02 3.05300000e+03
 2.00000000e+03 2.41600000e+03 3.33400000e+03 2.54100000e+03
 2.92500000e+03 2.93400000e+03 1.75000000e+03 1.80300000e+03
 1.86300000e+03 2.40500000e+03 1.64000000e+03 1.89000000e+02
 4.98300000e+03 2.16000000e+03 2.45100000e+03 1.79300000e+03
 1.83300000e+03 6.88000000e+02 4.60000000e+03 1.58700000e+03
 1.22900000e+03 2.33000000e+03 2.45800000e+03 3.23000000e+03
 2.16800000e+03 6.25000000e+03 5.05000000e+02 3.16700000e+03
 3.66700000e+03 5.26600000e+03 7.87300000e+03 1.98700000e+03
 9.23000000e+02 4.99600000e+03 4.23200000e+03 1.60000000e+03
 2.41700000e+03 1.62500000e+03 1.40000000e+03 2.00000000e+04
 2.40000000e+03 2.03300000e+03 3.23700000e+03 2.77300000e+03
 1.41700000e+03 1.71900000e+03 4.30000000e+03 1.61200008e+01
 2.34000000e+03 1.85100000e+03 5.06400000e+03 1.99300000e+03
 1.21000000e+03 1.37600000e+03 1.71000000e+03 1.25500000e+03
 1.73300000e+03 2.46600000e+03 2.56900000e+03 2.18800000e+03
 1.66400000e+03 2.91700000e+03 2.07900000e+03 1.50000000e+03
 4.64800000e+03 1.01400000e+03 1.87200000e+03 3.15000000e+03
 2.43600000e+03 2.15700000e+03 9.13000000e+02 1.70000000e+03
 4.41600000e+03 3.68300000e+03 5.62400000e+03 1.48300000e+03
 3.01300000e+03 1.28700000e+03 2.00400000e+03 2.03500000e+03
 6.66600000e+03 3.66600000e+03 3.42800000e+03 1.63200000e+03
 1.91500000e+03 1.74200000e+03 1.42400000e+03 7.16600000e+03
 1.30200000e+03 2.04200000e+03 3.90600000e+03 5.36000000e+02
 2.84500000e+03 2.52400000e+03 1.95000000e+03 1.78300000e+03
 2.01600000e+03 3.25000000e+03 4.26600000e+03 1.03200000e+03
 2.66900000e+03 2.30600000e+03 2.42000000e+02 2.06400000e+03
 4.61000000e+02 2.21000000e+03 2.73900000e+03 2.23200000e+03
 3.38370000e+04 1.52200000e+03 3.41600000e+03 3.30000000e+03
 1.00000000e+03 2.79200000e+03 4.30100000e+03 1.41100000e+03
 2.40000000e+02]
[128.  66. 120. 141. 267.  95. 158. 168. 349.  70. 109. 200. 114.  17.
 125.  76. 133. 104. 315. 116. 112. 191. 122. 110.  35.  74. 106. 320.
 144. 184.  80.  47. 134.  44. 100. 286.  97.  96. 135. 180.  99. 165.
 258. 126. 312. 136. 172.  81. 187. 113. 176. 111. 167.  50. 210. 175.
 131. 188.  25. 137. 115. 151. 160. 225. 216.  94. 139. 118. 185. 154.
 259. 194. 370. 102. 290.  84.  88. 242. 129.  30. 152. 244. 600. 255.
  98. 275. 121.  75.  63. 700.  87. 101. 495.  73. 260. 108.  48. 164.
 170.  83.  90. 166. 124.  55.  59. 127. 214. 240. 130.  72.  60. 138.
  42. 280. 140. 155. 123. 201. 279. 192. 304. 150. 207. 436.  78.  54.
  89. 143.  93. 105. 132. 480.  56. 159. 300. 376.  67. 117.  71. 490.
 182. 173.  46. 228. 308. 236. 570. 380. 296. 156. 103.  45.  65.  53.
 360.  62. 218. 178. 239. 405. 148. 149. 153. 162. 230.  86. 234. 246.
 500. 119. 107. 209. 208. 243.  40. 250. 311. 400. 161. 324. 157. 145.
 181.  26. 211.   9. 186. 205.  36. 146. 292. 142. 496. 253.]
[360 120 180  60 300 480 240  36  84]
[1. 0.]
<StringArray>
['Rural', 'Urban', 'Semiurban']
Length: 3, dtype: str
<StringArray>
['N', 'Y']
Length: 2, dtype: str

In [52]:
!mamba install scikit-learn

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, scikit-learn
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.8574000000003725 seconds
  Name                Version    Build                Channel
---------------------------------------------------------------------------
+ brotli-python       1.2.0      py313ha26e73d_2      emscripten-forge-4x
+ certifi             2026.6.17  pyhd8ed1ab_0         conda-forge
+ charset-normalizer  3.4.7      pyhd8ed1ab_0         conda-forge
+ idna                3.18       pyhcf101f3_0         conda-forge
+ joblib              1.5.3      py313h1804a44_3      emscripten-forge-4x
+ narwhals            2.22.1     pyhcf101f3_0         conda-forge
+ pysocks             1.7.1      py313h1804a44_3      emscripten-forge-4x
+ requests            2.34.2     pyhcf101f3_0         conda-forge
+ scikit-learn        1.9.0      np23py313hb9816c2_0  emscripten-forge-4x
+ setuptools          82.0.1     pyh332efcf_0         conda-forge
+ threadpoolctl       3.6.0      pyhecae5ae_0         conda-forge
+ urllib3             2.2.2      pyhd8ed1ab_0         conda-forge

In [84]:
#dummy encoding or one hot encoding for the categorical columns
binary_cols = ['Gender','Married','Education','Loan_Status','Self_Employed','Credit_History']
df[binary_cols] = pd.get_dummies(df[binary_cols],drop_first = True, dtype = int)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Property_Area'] = le.fit_transform(df['Property_Area'])

df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1.0,1,1,1,0,4583,1508.0,128.0,360,0,0,0
2,1.0,1,0,1,1,3000,0.0,66.0,360,1,2,0
3,1.0,1,0,1,1,2583,2358.0,120.0,360,0,2,1
4,1.0,1,0,0,1,6000,0.0,141.0,360,0,2,0
5,1.0,1,2,1,1,5417,4196.0,267.0,360,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,1.0,0,0,0,1,2900,0.0,71.0,360,0,0,0
610,1.0,1,3,1,1,4106,0.0,40.0,180,0,0,0
611,1.0,1,1,1,1,8072,240.0,253.0,360,0,2,0
612,1.0,1,2,1,1,7583,0.0,187.0,360,0,2,0
613,0.0,0,0,0,0,4583,0.0,133.0,360,1,1,0

In [85]:
df.to_csv('Cleaned_csv', index = False)

In [86]:
df['Income'] =  df['ApplicantIncome']+df['CoapplicantIncome']
df.drop(columns = ['ApplicantIncome','CoapplicantIncome'], inplace = True)

In [87]:
df

,Gender,Married,Dependents,Education,Self_Employed,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Income
1,1.0,1,1,1,0,128.0,360,0,0,0,6091.0
2,1.0,1,0,1,1,66.0,360,1,2,0,3000.0
3,1.0,1,0,1,1,120.0,360,0,2,1,4941.0
4,1.0,1,0,0,1,141.0,360,0,2,0,6000.0
5,1.0,1,2,1,1,267.0,360,1,2,0,9613.0
...,...,...,...,...,...,...,...,...,...,...,...
609,1.0,0,0,0,1,71.0,360,0,0,0,2900.0
610,1.0,1,3,1,1,40.0,180,0,0,0,4106.0
611,1.0,1,1,1,1,253.0,360,0,2,0,8312.0
612,1.0,1,2,1,1,187.0,360,0,2,0,7583.0
613,0.0,0,0,0,0,133.0,360,1,1,0,4583.0